version: 0.2
phases:
  pre_build:
    commands:
      - echo "🔧 Starting application build..."
      - echo "ENVIRONMENT = $ENVIRONMENT"
      - echo "SERVICE_TYPE = $SERVICE_TYPE"
      - echo "IMAGE_TAG = $IMAGE_TAG"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

      # Only clone storefront (domain-listener removed)
      - git clone https://github.com/AITeeToolkit/storefront.git source-repo
      - cd source-repo

  build:
    commands:
      - |
        if [ "$SERVICE_TYPE" = "api" ]; then
          DOCKERFILE_PATH="api/Dockerfile"
          BUILD_CONTEXT="api"
          ECR_REPO="api"
        elif [ "$SERVICE_TYPE" = "web" ]; then
          DOCKERFILE_PATH="multisite/Dockerfile"
          BUILD_CONTEXT="multisite"
          ECR_REPO="web"
        else
          echo \"❌ Unknown SERVICE_TYPE: $SERVICE_TYPE\"
          exit 1
        fi

        echo \"🚀 Building Docker image for $SERVICE_TYPE...\"
        docker build -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG} \\
          -f $DOCKERFILE_PATH $BUILD_CONTEXT

  post_build:
    commands:
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}
      - echo \"✅ Image pushed: ${ECR_REPO}:${IMAGE_TAG}\"