version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing CDK and Python dependencies..."
      - npm install -g aws-cdk
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "🏗️ Starting CDK infrastructure deployment..."
      - echo "Stacks to deploy: $STACK_NAMES"

  build:
    commands:
      - |
        for stack in $STACK_NAMES; do
          echo "🚀 Deploying stack: $stack"
          cdk deploy "$stack" --require-approval never
        done

  post_build:
    commands:
      - echo "✅ All CDK stacks deployed successfully"