version: 0.2

env:
  variables:
    CDK_ENV: dev
    CDK_IMAGE_TAG: v1.2.3
    PYTHON_VERSION: 3.11

phases:
  install:
    runtime-versions:
      python: ${PYTHON_VERSION}
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - cdk synth
      - cdk deploy --require-approval never --all