name: production
url: https://console.aws.amazon.com/ecs/home?region=us-east-1#/clusters
protection_rules:
  - type: required_reviewers
    required_reviewers:
      - users: []
      - teams: []
  - type: wait_timer
    minutes: 5
deployment_branch_policy:
  protected_branches: true
  custom_branch_policies: false
