name: staging
url: https://console.aws.amazon.com/ecs/home?region=us-east-1#/clusters
protection_rules: []
deployment_branch_policy:
  protected_branches: false
  custom_branch_policies: true
  custom_branches:
    - main
    - develop
