name: Build and Deploy (Web + API)

on:
  push:
    tags:
      - 'v*'
  workflow_call:
    inputs:
      environment:
        description: Environment
        required: true
        default: dev
        type: string
      image_tag:
        description: Docker image tag (e.g., v1.2.3)
        required: false
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        default: dev
        type: choice
        options:
          - dev
          - staging
          - prod
      image_tag:
        description: Docker image tag (e.g., v1.2.3)
        required: false
        type: string

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/storefront/${{ inputs.environment || github.event.inputs.environment || 'dev' }}
  IMAGE_TAG: ${{ inputs.image_tag || github.event.inputs.image_tag || github.ref_name }}
  PYTHON_VERSION: "3.11"
  CDK_ENV: ${{ inputs.environment || github.event.inputs.environment || 'dev' }}

jobs:
  login-to-aws:
    name: Login to AWS & ECR
    runs-on: ubuntu-latest
    outputs:
      login-done: "true"
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_CODEBUILD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CODEBUILD_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        run: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

  build-and-push-api:
    name: Build & Push API Image
    runs-on: ubuntu-latest
    needs: login-to-aws
    steps:
      - uses: actions/checkout@v4
      
      - name: Checkout storefront repository
        uses: actions/checkout@v4
        with:
          repository: AITeeToolkit/storefront
          token: ${{ secrets.GH_TOKEN }}
          path: storefront

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_CODEBUILD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CODEBUILD_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        run: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build API Docker Image
        run: |
          docker build -t $ECR_REGISTRY/api:${IMAGE_TAG} -t $ECR_REGISTRY/api:latest ./storefront/api

      - name: Push API Image
        run: |
          docker push $ECR_REGISTRY/api:${IMAGE_TAG}
          docker push $ECR_REGISTRY/api:latest

  build-and-push-web:
    name: Build & Push Web Image
    runs-on: ubuntu-latest
    needs: login-to-aws
    steps:
      - uses: actions/checkout@v4
      
      - name: Checkout storefront repository
        uses: actions/checkout@v4
        with:
          repository: AITeeToolkit/storefront
          token: ${{ secrets.GH_TOKEN }}
          path: storefront

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_CODEBUILD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CODEBUILD_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        run: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build Web Docker Image
        run: |
          docker build -t $ECR_REGISTRY/web:${IMAGE_TAG} -t $ECR_REGISTRY/web:latest ./storefront/multisite

      - name: Push Web Image
        run: |
          docker push $ECR_REGISTRY/web:${IMAGE_TAG}
          docker push $ECR_REGISTRY/web:latest

  deploy-cdk:
    name: Deploy CDK Stacks
    runs-on: ubuntu-latest
    needs: [build-and-push-api, build-and-push-web]
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_CODEBUILD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CODEBUILD_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup Node.js for CDK
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install CDK CLI
        run: npm install -g aws-cdk

      - name: Install Python dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: CDK Bootstrap
        run: |
          source .venv/bin/activate
          cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_ID }}/us-east-1

      - name: CDK Deploy All Stacks
        env:
          CDK_IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          source .venv/bin/activate
          cdk deploy --require-approval never --all

          
      - name: Post deployment notification
        uses: actions/github-script@v7
        with:
          script: |
            const imageTag = '${{ env.IMAGE_TAG }}';
            const environment = '${{ env.CDK_ENV }}';
            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: `🎉 **Application Deployed Successfully**\n\n` +
                    `- **Environment**: ${environment}\n` +
                    `- **Image Tag**: ${imageTag}\n` +
                    `- **Status**: ✅ Success\n` +
                    `- **Timestamp**: ${new Date().toISOString()}`
            });