name: Build and Deploy (Web + API)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        default: dev
        type: choice
        options:
          - dev
          - staging
          - prod
      image_tag:
        description: Docker image tag (e.g., v1.2.3)
        required: false

env:
  AWS_REGION: us-east-1
  PYTHON_VERSION: "3.11"
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
  IMAGE_TAG: ${{ github.event.inputs.image_tag || github.ref_name }}

jobs:
  login-to-aws:
    name: Login to AWS & ECR
    runs-on: ubuntu-latest
    outputs:
      login-done: "true"
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        run: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

  build-and-push-api:
    name: Build & Push API Image
    runs-on: ubuntu-latest
    needs: login-to-aws
    if: github.event_name == 'push' || github.event.inputs.image_tag == ''
    steps:
      - uses: actions/checkout@v4

      - name: Build API Docker Image
        run: docker build -t $ECR_REGISTRY/api:${IMAGE_TAG} ./storefront/api

      - name: Push API Image
        run: docker push $ECR_REGISTRY/api:${IMAGE_TAG}

  build-and-push-web:
    name: Build & Push Web Image
    runs-on: ubuntu-latest
    needs: login-to-aws
    if: github.event_name == 'push' || github.event.inputs.image_tag == ''
    steps:
      - uses: actions/checkout@v4

      - name: Build Web Docker Image
        run: docker build -t $ECR_REGISTRY/web:${IMAGE_TAG} ./storefront/multisite

      - name: Push Web Image
        run: docker push $ECR_REGISTRY/web:${IMAGE_TAG}

  deploy-cdk:
    name: Deploy CDK Stacks
    runs-on: ubuntu-latest
    needs: [build-and-push-api, build-and-push-web]
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: CDK Deploy
        env:
          CDK_IMAGE_TAG: ${{ env.IMAGE_TAG }}
          CDK_ENV: ${{ github.event.inputs.environment || 'dev' }}
        run: |
          source .venv/bin/activate
          cdk deploy --require-approval never --all