# .github/workflows/listener.yml
name: Listener Build

on:
  push:
    branches: ["**"]
    paths:
      - "scripts/listener_app.py"
      - "scripts/Dockerfile"

jobs:
  generate-tag:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.tag.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: tag
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
            echo "image_tag=${LATEST_TAG:-latest}" >> $GITHUB_OUTPUT
          else
            BRANCH_NAME=${GITHUB_REF#refs/heads/}
            SHORT_SHA=${GITHUB_SHA:0:7}
            echo "image_tag=${BRANCH_NAME}-${SHORT_SHA}" >> $GITHUB_OUTPUT
          fi

  build-listener:
    runs-on: ubuntu-latest
    needs: generate-tag
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker build --target listener -t ${{ secrets.ECR_REGISTRY }}/listener:${{ needs.generate-tag.outputs.image_tag }} ./scripts
          docker push ${{ secrets.ECR_REGISTRY }}/listener:${{ needs.generate-tag.outputs.image_tag }}

  trigger-infra:
    runs-on: ubuntu-latest
    needs: build-listener
    if: needs.build-listener.result == 'success'
    steps:
      - name: Trigger infra workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: AITeeToolkit/aws-fargate-cdk
          event-type: deploy-infra
          client-payload: |
            {
              "listener_tag": "${{ needs.generate-tag.outputs.image_tag }}",
              "components": { "listener": true }
            }