name: Build Listener Image

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      image_tag:
        required: true
        type: string
    secrets:
      AWS_CODEBUILD_ACCESS_KEY_ID:
        required: true
      AWS_CODEBUILD_SECRET_ACCESS_KEY:
        required: true
      AWS_ACCOUNT_ID:
        required: true

jobs:
  build-listener:
    name: Build & Push Listener Image
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_CODEBUILD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CODEBUILD_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        run: |
          ECR_REGISTRY=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/storefront/${{ inputs.environment }}
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REGISTRY
          echo "ECR_REGISTRY=$ECR_REGISTRY" >> $GITHUB_ENV

      - name: Build Listener Docker Image
        run: |
          echo "🔧 Building Listener image with tag: ${{ inputs.image_tag }}"
          docker build -t $ECR_REGISTRY/listener:${{ inputs.image_tag }} ./apps/listener
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            docker tag $ECR_REGISTRY/listener:${{ inputs.image_tag }} $ECR_REGISTRY/listener:latest
          fi

      - name: Push Listener Image
        run: |
          docker push $ECR_REGISTRY/listener:${{ inputs.image_tag }}
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            docker push $ECR_REGISTRY/listener:latest
          fi

      - name: Tag Git after successful build
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "listener-${{ inputs.image_tag }}"
          git push origin "listener-${{ inputs.image_tag }}"