name: Build Listener Image

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      force_build:
        required: false
        default: false
        type: boolean
    secrets:
      GH_TOKEN:
        required: true
      AWS_CODEBUILD_ACCESS_KEY_ID:
        required: true
      AWS_CODEBUILD_SECRET_ACCESS_KEY:
        required: true

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/storefront/${{ inputs.environment || 'dev' }}

jobs:
  detect-changes:
    name: Detect Listener Changes
    runs-on: ubuntu-latest
    outputs:
      listener_changed: ${{ steps.diff.outputs.listener_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v3
        id: diff
        with:
          filters: |
            listener_changed:
              - 'added|modified: apps/listener/**'
              - 'added|modified: apps/Dockerfile'
              - 'added|modified: apps/requirements.txt'

  build-listener:
    name: Build & Push Listener Image
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [detect-changes]
    if: ${{ inputs.force_build || needs.detect-changes.outputs.listener_changed == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_CODEBUILD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CODEBUILD_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Listener Image
        uses: docker/build-push-action@v5
        with:
          context: ./apps
          target: listener
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/listener:${{ inputs.image_tag }}
            ${{ github.ref == 'refs/heads/main' && format('{0}/listener:latest', env.ECR_REGISTRY) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max